config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.contrib.auth import views

from accounts.views import ChildStatusListView, ChildStatusDetailView, ChildStatusUpdateView, HomeListView
from config import settings
from users.views import ChildDeleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
    path('tasks/', include('task.urls')),
    path('ticket/', include('ticket.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api_v1/', include('api_v1.urls')),
    path('', HomeListView.as_view(), name='home'),
    path('admin_home/', TemplateView.as_view(template_name='admin_home.html'), name='admin_home'),
    path('graphs/', TemplateView.as_view(template_name='graphs.html'), name='graphs'),
    path('switch/', TemplateView.as_view(template_name='switch.html'), name='switch'),
    path('status/', ChildStatusListView.as_view(), name='status'),
    path('status/change/<int:pk>/', ChildStatusDetailView.as_view(), name='status_change'),
    path('status/delete/', ChildDeleteView.as_view(), name='selected_child_delete'),
    path('status/update/<int:pk>/', ChildStatusUpdateView.as_view(), name='status_update'),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/signup/', TemplateView.as_view(template_name='signup.html'), name='new_user'),
    path('accounts/password_change/', views.PasswordChangeView.as_view(), name="password_change"),
    path('accounts/password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password_reset/', views.PasswordResetCompleteView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task/urls.py
from django.views.generic import TemplateView
from django.urls import path

from task.views import TaskListView, TaskRegistView, TaskDeleteView, TaskUpdateView, TaskDetailView

# TaskInputView,

urlpatterns = [

    path('', TaskListView.as_view(), name='tasks'),
    path('regist/', TaskRegistView.as_view(), name='task_regist'),
    path('delete/', TaskDeleteView.as_view(), name='selected_task_delete'), ##DeleteViewはインスタンスいらない。単体消す用。
    path('update/<int:pk>', TaskUpdateView.as_view(), name='task_update'),
    path('detail/<int:pk>', TaskDetailView.as_view(), name='task_detail'),

]

users/models.py
from django.db import models

# Create your models here.
# 共通カラムを定義（appを超えるのは不可？）
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill

from task.models import Task
from ticket.models import Ticket


class CommonColumnModel(models.Model):
    """共通カラム"""

    class Meta:
        abstract = True

    create_datetime = models.DateTimeField(verbose_name='登録日時', auto_now_add=True)
    create_user = models.CharField(verbose_name='登録ユーザ', max_length=32, default='admin')
    update_datetime = models.DateTimeField(verbose_name='更新日時', auto_now=True)
    update_user = models.CharField(verbose_name='更新ユーザ', max_length=32, default='admin')
    delete_flg = models.BooleanField(verbose_name='削除フラグ', null=False, default=False)


class Parent(CommonColumnModel):
    """親モデル"""
    class Meta:
        #テーブル名を定義
        db_table = 'puser'
    #テーブルのカラムに対応するフィールドを定義
    photo = models.ImageField(verbose_name='写真', null=True, max_length=255, upload_to='parent/')
#    thumbnail = ImageSpecField(source='photo', processors=[ResizeToFill(200, 100)], format='JPEG', options={'quality': 80})

    def __str__(self):
        return str(self.pk)


class Child(CommonColumnModel):
    """子供モデル"""
    class Meta:
        #テーブル名を定義
        db_table = 'cuser'

    #テーブルのカラムに対応するフィールドを定義 appを超えたFKははれない？⇒　importすればよい
    puser = models.ForeignKey(Parent, verbose_name='親ユーザーID', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='名前', max_length=255)
    photo = models.ImageField(verbose_name='写真', null=True, max_length=255, upload_to='Child/')
 #   thumbnail = ImageSpecField(source='photo', processors=[ResizeToFill(200, 100)], format='JPEG', options={'quality': 80})

    def __str__(self):
        return str(self.name)


class Balance(CommonColumnModel):
    """残高"""
    class Meta:
        #テーブル名を定義
        db_table = 'balance'

    cuser = models.ForeignKey(Child, verbose_name='子ユーザーID', on_delete=models.CASCADE)
    balance = models.IntegerField(verbose_name='残高', default=0)

    def __str__(self):
        return str(self.cuser)

class Ticket_holding(CommonColumnModel):
    """保有チケット"""
    class Meta:
        #テーブル名を定義
        db_table = 'ticket_holding'

    cuser = models.ForeignKey(Child, verbose_name='子ユーザーid', on_delete=models.CASCADE)
    ticket = models.ForeignKey(Ticket, verbose_name='チケットID', on_delete=models.CASCADE)
    used_flg = models.IntegerField(verbose_name='利用フラグ', default=0)

    def __str__(self):
        return str(self.ticket)

class Request(CommonColumnModel):
    """リクエスト・承認"""
    class Meta:
        #テーブル名を定義
        db_table = 'request'

    cuser = models.ForeignKey(Child, verbose_name='子ユーザーID', on_delete=models.CASCADE)
    puser = models.ForeignKey(Parent, verbose_name='親ユーザーID', on_delete=models.CASCADE)
    task = models.ForeignKey(Task, verbose_name='タスクID', on_delete=models.CASCADE)
    status = models.IntegerField(verbose_name='ステータス', default=1)

    def __str__(self):
        return str(self.cuser)

class History(CommonColumnModel):
    class Meta:
        #テーブル名を定義
        db_table = 'history'
    ymd = models.DateTimeField(verbose_name='入出金日時')
    cuser = models.ForeignKey(Child, verbose_name='子ユーザーID', on_delete=models.CASCADE)
    task = models.ForeignKey(Task, verbose_name='タスクID', on_delete=models.PROTECT, null=True, blank=True)
    ticket = models.ForeignKey(Ticket, verbose_name='チケットID', on_delete=models.PROTECT, null=True, blank=True)
    amount = models.IntegerField(verbose_name='金額', null=True, blank=True)
    ticket_holding = models.ForeignKey(Ticket_holding, verbose_name='保有チケットID', on_delete=models.CASCADE, null=True, blank=True)
    kind = models.IntegerField(verbose_name='取引種類')
    # 1:獲得（タスクの承認） 2:購入 3:利用

    def __str__(self):
        return str(self.ymd)

# Histotyに統合
#class History_ticket(CommonColumnModel):
#    class Meta:
#        #テーブル名を定義
#        db_table = 'history_ticket'
#
#    ymd = models.DateTimeField(verbose_name='入出金日時')
#    ticket_holding = models.ForeignKey(Ticket_holding, verbose_name='チケット保有ID', on_delete=models.CASCADE)#
#
#    def __str__(self):
#        return str(self.ymd)

templates/children/apply_complete.html
{% extends "base.html" %}

{% block title %}申請完了{% endblock %}

{% block content %}

<p>
<h2>おてつだいをつたえたよ！</h2>
<h2>ママがみるまでまってね</h2>
</p>


<p>
<div class="col-xl-4 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2 w-80">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col-auto">
                    <img class="rounded-circle mr-3" src="/media/{{ child_data.photo }}" alt="" width="70" height="70">
                </div>
                <div class="col mr-2 text-center">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{ child_data.name }}</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800">
                          {% if balance_data.balance == None %}
                            <div class="pay">¥0</div>
                            {% else %}
                            <div class="pay">¥{{ balance_data.balance }}</div>
                            {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</p>

<h2>ママのOKまち</h2>
<p>
{% for request in request_list %}
{{ request.task.task_name }}:¥{{ request.task.price }}<br>
{% endfor %}
</p>

<a href="{% url 'child_home' child_data.id %}">Homeへ</a>

{% endblock %}

templates/children/apply_task.html
{% extends "base.html" %}

{% block title %}タスクの申請{% endblock %}
{% block content %}

<p>
<h2>なんのおてつだいをした？</h2>
</p>

<div class="col-xl-4 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2 w-80">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col-auto">
                    <img class="rounded-circle mr-3" src="/media/{{ child_data.photo }}" alt="" width="70" height="70">
                </div>
                <div class="col mr-2 text-center">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{ child_data.name }}</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800">
                          {% if balance_data.balance == None %}
                            <div class="pay">¥0</div>
                            {% else %}
                            <div class="pay">¥{{ balance_data.balance }}</div>
                            {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<form method="post" action="{% url 'task_apply_update' %}">
    {% csrf_token %}

{#  use_ticketをベースにつくりなおす #}

    <p>
    {% for list in object_list %}
    <div class="custom-control custom-switch">
    <input type="checkbox" class="custom-control-input" id="switch{{ list.id }}" name="apply_task_list" value="{{ list.id }}">
    <label class="custom-control-label" for="switch{{ list.id }}">
        {{ list.task_name }}: {{ list.price }}ペイ
    </label><br>
    </div>
    {% endfor %}
    </p>

    <input type="hidden" name="apply_child_id" value="{{ child_data.id }}" />

    <div class="container">
        <div class="row" >
            <div class="col-md-6 mb-3">
                <button class="btn btn-outline-primary w-100 btn-lg" ><i class="fas fa-chalkboard-teacher mr-1"></i>ママにおしえる</button>
            </div>
        </div>
    </div>

</form>

<p>
<a href="{% url 'child_home' child_data.id %}">こどもがめんにもどる</a>
</p>

{% endblock %}

templates/children/child_history.html
{% extends "base.html" %}

{% block title %}履歴{% endblock %}

{% block content %}

 <h4 class="mt-4 border-bottom">{{ child_data.name }}の履歴</h4>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">日時</th>
          <th scope="col">種別</th>
          <th scope="col">タスク名</th>
          <th scope="col">チケット名</th>
          <th scope="col">金額</th>
        </tr>
      </thead>
      <tbody>
        {% for data in object_list %}
        <tr>
          <th scope="row">{{ data.ymd }}</th>
          {% if data.kind == 1 %}
          <td>獲得</td>
          {% elif data.kind == 2 %}
          <td>購入</td>
          {% elif data.kind == 3 %}
          <td>利用</td>
          {% else %}
          <td>不明</td>
          {% endif %}
          <td>{% if data.task == None %} - {% else %}{{ data.task }}{% endif %}</td>
          <td>{% if data.ticket == None %} - {% else %}{{ data.ticket }}{% endif %}</td>
          <td>{% if data.amount == None %} - {% else %}{{ data.amount }}{% endif %}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

{% include 'general/pagination.html' %}

<p>
<a href="{% url 'child_home' child_data.id %}">こどもがめんにもどる</a>
</p>

{% endblock %}

templates/children/child_home.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block title %}こどもホーム{% endblock %}

{% block content %}

<p>
<div class="col-xl-4 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2 w-80">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col-auto">
                    <img class="rounded-circle mr-3" src="/media/{{ child_data.photo }}" alt="" width="70" height="70">
                </div>
                <div class="col mr-2 text-center">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{ child_data.name }}</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800">
                          {% if balance_data.balance == None %}
                            <div class="pay">¥0</div>
                            {% else %}
                            <div class="pay">¥{{ balance_data.balance }}</div>
                            {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</p>

<p>
    <ul>
    {% if top_task.task__task_name == None %}
        <li>なにもやってないよ！</li>
    {% else %}
        <li>{{ child_data.name }}は{{ top_task.task__task_name }}をたくさんやってくれてる</li>
    {% endif %}

    {% if top_ticket.ticket__ticket_name == None %}
        <li>なにもやってないよ！</li>
    {% else %}
        <li>{{ child_data.name }}は{{ top_ticket.ticket__ticket_name }}ばっかりやってる</li>
    {% endif %}
    </ul>
</p>



<div class="container">
 <div class="row" >
   <div class="col-md-3 mb-3">
    <button type="button" class="btn btn-outline-primary w-100 btn-lg" onclick="location.href='{% url 'apply_task' child_data.id %}'"><i class="fas fa-chalkboard-teacher mr-1"></i>おてつだいをいう</button>
   </div>
   <div class="col-md-3 mb-3">
    <button type="button" class="btn btn-outline-success w-100 btn-lg" onclick="location.href='{% url 'use_ticket' child_data.id %}'"><i class="fas fa-ticket-alt mr-1"></i>チケットをつかう</button>
   </div>
   <div class="col-md-3 mb-3">
    <button type="button" class="btn btn-outline-danger w-100 btn-lg" onclick="location.href='{% url 'ticket_shop' child_data.id %}'"><i class="fas fa-shopping-bag mr-1"></i>チケットショップ</button>
   </div>
   <div class="col-md-3 mb-3">
    <button type="button" class="btn btn-outline-warning w-100 btn-lg" onclick="location.href='{% url 'children_history' child_data.id %}'"><i class="fas fa-history mr-1"></i>りれきをみる</button>
   </div>
 </div>
</div>

<!-- <h2><a href="{% url 'apply_task' child_data.id %}">タスクを申請する</a></h2>
 <h2><a href="{% url 'use_ticket' child_data.id %}">チケットを使う</a></h2>
 <h2><a href="{% url 'ticket_shop' child_data.id %}">チケットショップ</a></h2>
 <h2><a href="{% url 'children_history' child_data.id %}">履歴を見る</a></h2>
 <h2><a href="{% url 'home' %}">ホームに戻る</a></h2>
-->

{% endblock %}

templates/children/child_home_old.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block title %}こどもホーム{% endblock %}

{% block content %}

<div class="card w-75 shadow-sm mx-auto">
    <div class="container">
    <div class="row no-gutters">
        <div class="col-md-4">
            <svg class="bd-placeholder-img" width="100%" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Image">
                <title>Placeholder</title><rect fill="#868e96" width="100%" height="100%"/>
                <text fill="#dee2e6" dy=".3em" x="50%" y="50%">Image</text>
            </svg>
        </div>
        <div class="col-md-8">
            <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs" >
                    <li class="nav-item">
                        <a class="nav-link active" href="#info" data-toggle="tab">Info</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#ticket" data-toggle="tab">Ticket</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#data" data-toggle="tab">Data</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li>
                </ul>
            </div>
            <div class="card-body tab-content">
                <div class="tab-pane active" id="info">
                    <h6 class="card-title">{{ child_data.name }}</h6>

                    {% if balance_data.balance == None %}
                   <h4 class="card-subtitle">0 mamapay</h4>
                    {% else %}
                    <h4 class="card-subtitle">{{ balance_data.balance }} mamapay</h4>
                    {% endif %}

                    <p class="card-text">
                        <ul>
                            <li>{{ child_data.name }}は靴磨きをたくさんやってくれてる</li>
                            <li>{{ child_data.name }}はゲームばっかりやってる</li>
                        </ul>
                    </p>

                    <!--アイコン-->
                    <div class="container">
                        <div class="row" >
                            <div class="col-md-3 mb-3">
                                <button type="button" class="btn btn-outline-primary w-100" onclick="location.href='{% url 'apply_task' child_data.id %}'"><i class="fas fa-chalkboard-teacher mr-1"></i></button>
                            </div>
                            <div class="col-md-3 mb-3">
                                <button type="button" class="btn btn-outline-success w-100" onclick="location.href='{% url 'use_ticket' child_data.id %}'"><i class="fas fa-ticket-alt mr-1"></i></button>
                            </div>
                            <div class="col-md-3 mb-3">
                                <button type="button" class="btn btn-outline-danger w-100 " onclick="location.href='{% url 'ticket_shop' child_data.id %}'"><i class="fas fa-shopping-bag mr-1"></i></button>
                            </div>
                            <div class="col-md-3 mb-3">
                                <button type="button" class="btn btn-outline-warning w-100" onclick="location.href='{% url 'children_history' child_data.id %}'"><i class="fas fa-history mr-1"></i></button>
                            </div>
                        </div>
                    </div>
                    <!-- /アイコン-->
                </div>
                <div class="tab-pane" id="ticket">
                    持ってるチケット
                </div>
                <div class="tab-pane" id="data">
                    データがはいる
                </div>
            </div>
        </div>
    </div>
</div>
</div>


<div class="container">
 <div class="row" >
   <div class="col-md-3 mb-3">
    <button type="button" class="btn btn-outline-primary w-100 btn-lg" onclick="location.href='{% url 'apply_task' child_data.id %}'"><i class="fas fa-chalkboard-teacher mr-1"></i>タスクを申請する</button>
   </div>
   <div class="col-md-3 mb-3">
    <button type="button" class="btn btn-outline-success w-100 btn-lg" onclick="location.href='{% url 'use_ticket' child_data.id %}'"><i class="fas fa-ticket-alt mr-1"></i>チケットをつかう</button>
   </div>
   <div class="col-md-3 mb-3">
    <button type="button" class="btn btn-outline-danger w-100 btn-lg" onclick="location.href='{% url 'ticket_shop' child_data.id %}'"><i class="fas fa-shopping-bag mr-1"></i>チケットショップ</button>
   </div>
   <div class="col-md-3 mb-3">
    <button type="button" class="btn btn-outline-warning w-100 btn-lg" onclick="location.href='{% url 'children_history' child_data.id %}'"><i class="fas fa-history mr-1"></i>りれきをみる</button>
   </div>
 </div>
</div>

<!-- <h2><a href="{% url 'apply_task' child_data.id %}">タスクを申請する</a></h2>
 <h2><a href="{% url 'use_ticket' child_data.id %}">チケットを使う</a></h2>
 <h2><a href="{% url 'ticket_shop' child_data.id %}">チケットショップ</a></h2>
 <h2><a href="{% url 'children_history' child_data.id %}">履歴を見る</a></h2>
 <h2><a href="{% url 'home' %}">ホームに戻る</a></h2>
-->

{% endblock %}

templates/children/child_status.html
{% extends "base.html" %}

{% block title %}こどもを見る{% endblock %}

{% block content %}


<h2>{{ balance.cuser }}の申請</h2>

<p>
<div class="col-xl-4 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2 w-80">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col-auto">
                    <img class="rounded-circle mr-3" src="/media/{{ balance.cuser.photo }}" alt="" width="70" height="70">
                </div>
                <div class="col mr-2 text-center">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">{{ balance.cuser }}</div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800">
                          {% if balance.balance == None %}
                            <div class="pay">¥0</div>
                            {% else %}
                            <div class="pay">¥{{ balance.balance  }}</div>
                            {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</p>

<form method="post" action="child_approve">
    {% csrf_token %}

    {% if not object_list %}
    <p class="text-center">{{ balance.cuser }}の申請はありません</p>
    {% else %}
        {% for list in object_list %}
    <div class="custom-control custom-switch">
    <input type="checkbox" class="custom-control-input" id="switch{{ list.id }}" name="approve_task_list" value="{{ list.id }}">
    <label class="custom-control-label" for="switch{{ list.id }}">
        {{ list.task }}</input>
    </label><br>
    </div>
        {% endfor %}

    <input type="hidden" name="approve_child_id" value="{{ balance.cuser_id }}" />

   　<div class="container">
      <div class="row" >
            <div class="col-md-6 mb-3">
                <button class="btn btn-outline-primary w-100 btn-lg" ><i class="fas fa-chalkboard-teacher mr-1"></i>承認する</button>
            </div>
            <div class="col-md-6 mb-3">
                <button class="btn btn-outline-success w-100 btn-lg" type="submit" formaction="child_approve_delete"><i class="fas fa-chalkboard-teacher mr-1"></i>却下する</button>
            </div>
        </div>
    </div>

    {% endif %}
</form>


{# <p><a href="{% url 'children_history' balance.cuser_id %}">タスクとチケット購入履歴を見る</a></p> #}
<h5><a href="{% url 'admin_home' %}">戻る</a></h5>

{% endblock %}

templates/children/children.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block title %}こどもを選択{% endblock %}

{% block content %}

<h2>こどもを選択</h2>

 {% for data in object_list %}
 <p>
<div class="col-xl-4 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2 w-80 href="{% url 'child_status' data.id %}">
        <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col-auto">
                    <img class="rounded-circle mr-3" src="/media/{{ data.cuser.photo }}" alt="" width="70" height="70">
                </div>
                <div class="col mr-2 text-center">
                 <div class="text-xs font-weight-bold text-primary text-uppercase mb-1"><a href="{% url 'child_status' data.id %}">{{ data.cuser }}</a></div>
                    <div class="h5 mb-0 font-weight-bold text-gray-800">
                          {% if data.balance == None %}
                            <div class="pay">¥0</div>
                            {% else %}
                            <div class="pay">¥{{ data.balance  }}</div>
                            {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</p>
{% endfor %}




<h5><a href="{% url 'admin_home' %}">戻る</a></h5>

{% endblock %}

templates/children/children_change.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block title %}子供の変更{% endblock %}

{% block content %}
 <h2>こどもステータス変更</h2>
{{ child.name }}のステータス

<form method="post" action="{% url 'children_regist' data.id %}" enctype="multipart/form-data">
 {% csrf_token %}

 {{ form.as_p }}

 <p><input type="submit" value="変更する" class="btn btn-primary"></p>
</form>


{% endblock %}

templates/children/children_regist.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block title %}こどもを登録{% endblock %}

{% block content %}

<h2>写真のアップロード</h2>


<form method="post" enctype="multipart/form-data">
{% csrf_token %}
 {# csrf_token はpostメソッドを使うときは必ず入れる #}
 {# {% bootstrap_form form %} #}

{{ c_form.as_p }}
{{ s_form.as_p }}

 <button class="btn btn-primary" type="submit">登録する</button>
</form>

{% endblock %}